#!/bin/bash

# Usage:
# graphsc-speed.sh graphsc_options testname

trap 'kill $(jobs -pr) 2> /dev/null; echo; exit 1' SIGINT SIGTERM

testname="${!#}"
opts="${@:1:$(($#-1))}"

cp "reformatted/speed-benchmark/$testname/data" "$MY_TEMP_DIR/data"
cp "reformatted/speed-benchmark/$testname/Test.hs" "$MY_TEMP_DIR/CorrectTest.hs"

"$(dirname "$0")/../graphsc" -o "$MY_TEMP_DIR/GeneratedTest.hs" "$@"

# We should preserve original type definitions
cat "reformatted/speed-benchmark/$testname/Test.hs" | sed -n '1,/-- function definitions/p' > "$MY_TEMP_DIR/Test.hs"
cat "$MY_TEMP_DIR/GeneratedTest.hs" | sed -n '/-- function definitions/,$p' >> "$MY_TEMP_DIR/Test.hs"

GHC_OPTIONS="-O" "$(dirname "$0")/run-test-with-main.sh" "$MY_TEMP_DIR/Test.hs" "$(dirname "$0")/Speed.hs" run < "$MY_TEMP_DIR/data" | tee >(grep -q "correct True"; echo $? > correctness)

res="$?"
grepres="$(cat correctness)"

if [[ -z "$grepres" ]]; then
	exit 1
elif [[ "$grepres" = 0 ]]; then
        exit "$res"
else
	exit 55
fi

