#!/bin/bash

testname="${!#}"
opts="${@:1:$(($#-1))}"

cp "reformatted/hipspec-total/$testname/Test.hs" "$MY_TEMP_DIR/Test.hs"

cd "$MY_TEMP_DIR"

hipspec -a $opts Test.hs | tee >(grep -q "Proved prop_0"; echo $? > grep_result)

res="$?"
grepres="$(cat grep_result)"

if [[ -z "$grepres" ]]; then
	exit 1
else
	exit "$grepres"
fi

